### ISSUE TITLE
Egg image resolution should be reduced

### ISSUE THREAD

**Issue by ashgillman** [jcuroboclub/White-Roofs#8]
~200x200 should be appropriate.

**Comment by AKST** [comment]
yeah they're pretty huge now that I think about that, making them smaller should speed up load times, on a side note the app.js or whatever the source is compiled to should probably be minified for a speed up as well. The speed up will be most noticeable on mobile phones

**Comment by ashgillman** [comment]
Fixed by @AKST [here](https://github.com/jcuroboclub/White-Roofs/pull/10) b7efc7f471b139e509f2fe3290ed25caaf73cf9b
