### ISSUE TITLE
LiveReload in Production

### ISSUE THREAD

**Issue by ashgillman** [jcuroboclub/White-Roofs#9]
LiveReload is still included in production.

Need to set it to be included for gulp tasks watch and build, but not for gulp task deploy.

Any simple suggestions @AKST? Otherwise I will work it.

**Comment by AKST** [comment]
oh right, yeah just run the build like

```
ENV=PROD make build
```

and it will just remove it from the index.html when moving it to the output directory. I foresaw this and decided to setup a preprocessor for the [html in the build](https://github.com/jcuroboclub/White-Roofs/blob/master/web/gulpfile.coffee#L60).

**Comment by ashgillman** [comment]
Thanks @AKST https://github.com/jcuroboclub/White-Roofs/pull/11 34b7e427c68d08ad22c483b9d109a061abcc15a9
